### PR TITLE
Update Dockerfile for use with Raspberry Pi

### PR DESCRIPTION
**Pull request by tonyroberts**
And add docs for building/developing using docker and the Raspberry Pi.

### CODE REVIEW

**Comment by mmroden** [comment]
The behavior tests do not pass with this PR.

When run from the main branch, this test passes:

>@wip
>Feature: Runs backend from a Docker image # features/runs_backend_from_docker_image.feature:2
>
>  @slow
>  Scenario:                                                                    # features/runs_backend_from_docker_image.feature:5
>    Given A running Docker image on port 8000                                  # features/steps/runs_backend_from_docker_image.py:10 2.476s
>    When I listen for packets                                                  # features/steps/runs_backend_from_docker_image.py:21 0.004s
>    Then there will be a JSON packet sent every 1.0 seconds                    # features/steps/runs_backend_from_docker_image.py:27 6.519s
>    And that JSON packet will have several keys named with 'patient-{0-index}' # features/steps/runs_backend_from_docker_image.py:41 0.000s
>    And those keys will refer to the descriptors                               # features/steps/runs_backend_from_docker_image.py:50 0.000s

When run from this branch, that test fails:

>@wip
>Feature: Runs backend from a Docker image # features/runs_backend_from_docker_image.feature:2
>
>  @slow
>  Scenario:                                                                    # features/runs_backend_from_docker_image.feature:5
>    Given A running Docker image on port 8000                                  # features/steps/runs_backend_from_docker_image.py:10 2.523s
>    When I listen for packets                                                  # features/steps/runs_backend_from_docker_image.py:21 0.800s
>    Then there will be a JSON packet sent every 1.0 seconds                    # features/steps/runs_backend_from_docker_image.py:27 7.904s
>      Assertion Failed: Fails to send packets at 1 Hz
>
>    And that JSON packet will have several keys named with 'patient-{0-index}' # None
>    And those keys will refer to the descriptors                               # None

I deleted all my docker images and ran a second time to see if I can reproduce, and I can.  The second failure was:

>@wip
>Feature: Runs backend from a Docker image # features/runs_backend_from_docker_image.feature:2
>
>  @slow
>  Scenario:                                                                    # features/runs_backend_from_docker_image.feature:5
>    Given A running Docker image on port 8000                                  # features/steps/runs_backend_from_docker_image.py:10 2.512s
>    When I listen for packets                                                  # features/steps/runs_backend_from_docker_image.py:21 1.058s
>      Traceback (most recent call last):
>        File "/Users/mark.roden/github-src/prs/project-tetra-display/venv/lib/python3.9/site-packages/behave/model.py", line 1329, in run
>          match.run(runner.context)
>        File "/Users/mark.roden/github-src/prs/project-tetra-display/venv/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
>          self.func(context, *args, **kwargs)
>        File "features/steps/runs_backend_from_docker_image.py", line 24, in step_impl
>          context.ws = ws_connect_retry(uri)
>        File "/Users/mark.roden/github-src/prs/project-tetra-display/basic_websocket.py", line 15, in ws_connect_retry
>          raise Exception("Could not connect")
>      Exception: Could not connect
>
>    Then there will be a JSON packet sent every 1.0 seconds                    # None
>    And that JSON packet will have several keys named with 'patient-{0-index}' # None
>    And those keys will refer to the descriptors                               # None
>
>
>Failing scenarios:
>  features/runs_backend_from_docker_image.feature:5

**Comment by mmroden** [comment]
Still failing:

>@wip
>Feature: Runs backend from a Docker image # features/runs_backend_from_docker_image.feature:2
>
>  @slow
>    Then there will be a JSON packet sent every 1.0 seconds                    # features/steps/runs_backend_from_docker_image.py:27 7.791s
>      Assertion Failed: Fails to send packets at 1 Hzeconds                    # features/steps/runs_backend_from_docker_image.py:27
>
>    And that JSON packet will have several keys named with 'patient-{0-index}' # None
>    And those keys will refer to the descriptors                               # None

What system are you running the tests on?  I'm running on a mac and can get a linux system going.  Are you using windows?

**Comment by tonyroberts** [comment]
Yep, Windows (WSL). It would make more sense if you can change the tests to
actually run in the pi though rather than always using docker. For now
maybe just try running it on the pi so you can verify it actually works
that way? It was very painful for me to actually get the tests to run at
all. I assumed that was because I was on Windows but either way they need
some work.

**Comment by mmroden** [comment]
What work, in specific, are you looking for?  To make things work on Windows?  The main branch tests run on mac and linux right now.  I can check on a pi, but the problem there is that many people develop on non-pi environments, and that's why we're using docker the way that we are.  

The problem of platform specificity is what's kept this work from moving forward, frankly.  There's nothing in this code that specifically excludes WSL, it's just that we don't have the capacity to test for it.  With this update do all the behave tests, as run through `./runtests.sh`, work for you?

**Comment by tonyroberts** [comment]
C:\github\tonyroberts\project-tetra-display\venv\Scripts\python.exe -m behave -v
Using defaults:
          color False
  show_snippets True
   show_skipped True
        dry_run False
    show_source True
   show_timings True
 stdout_capture True
 stderr_capture True
    log_capture True
 logging_format %(levelname)s:%(name)s:%(message)s
  logging_level 20
  steps_catalog False
        summary True
          junit False
          stage None
       userdata {}
 default_format pretty
   default_tags 
scenario_outline_annotation_schema {name} -- @{row.id} {examples.name}
Using default path "./features"
Trying base directory: C:\github\tonyroberts\project-tetra-display\features
Feature: Calculating tubing descriptors # features/calculating_tubing_descriptors.feature:1

  Scenario: Calculating descriptors                # features/calculating_tubing_descriptors.feature:3
    Given there are sensors connected              # features/steps/calculating_tubing_descriptors.py:7
    And there is a calculator to parse sensor data # features/steps/calculating_tubing_descriptors.py:12
    When data is requested from the sensors        # features/steps/calculating_tubing_descriptors.py:17
    Then the sensors yield all of the descriptors  # features/steps/calculating_tubing_descriptors.py:22

Feature: Discriptors are drawn to the display # features/descriptors_are_drawn_to_the_display.feature:1

  @fixture.browser.chrome
  Scenario: All values read 0.0                                            # features/descriptors_are_drawn_to_the_display.feature:4
    Given a file named index.html exists in static/                        # features/steps/descriptors_are_drawn_to_the_display.py:8
    And a file named style.css exists in static/                           # features/steps/descriptors_are_drawn_to_the_display.py:8
    And A running Docker image on port 8000                                # features/steps/runs_backend_from_docker_image.py:10
    And that docker image is ready to receive test data                    # features/steps/descriptors_are_drawn_to_the_display.py:17
    When a data packet is sent where all the leaf values are 0             # features/steps/descriptors_are_drawn_to_the_display.py:22
    Then all the values in the display will correspond to that data packet # features/steps/descriptors_are_drawn_to_the_display.py:32

  @fixture.browser.chrome
  Scenario: All values read 0.0 except patient 1 PEEP                                                                              # features/descriptors_are_drawn_to_the_display.feature:13
    Given a file named index.html exists in static/                                                                                # features/steps/descriptors_are_drawn_to_the_display.py:8
    And a file named style.css exists in static/                                                                                   # features/steps/descriptors_are_drawn_to_the_display.py:8
    And A running Docker image on port 8000                                                                                        # features/steps/runs_backend_from_docker_image.py:10
    And that docker image is ready to receive test data                                                                            # features/steps/descriptors_are_drawn_to_the_display.py:17
    When I send a JSON packet formatted for this display where the leave values are all 0.0 except PEEP for patient 1 which is 1.0 # features/steps/descriptors_are_drawn_to_the_display.py:50
    Then all the values in the display will correspond to that data packet                                                         # features/steps/descriptors_are_drawn_to_the_display.py:32

  @fixture.browser.chrome
  Scenario: One of the data values is a big number                                                                                    # features/descriptors_are_drawn_to_the_display.feature:22
    Given a file named index.html exists in static/                                                                                   # features/steps/descriptors_are_drawn_to_the_display.py:8
    And a file named style.css exists in static/                                                                                      # features/steps/descriptors_are_drawn_to_the_display.py:8
    And A running Docker image on port 8000                                                                                           # features/steps/runs_backend_from_docker_image.py:10
    And that docker image is ready to receive test data                                                                               # features/steps/descriptors_are_drawn_to_the_display.py:17
    When I send a JSON packet formatted for this display where the leave values are all 0.0 except PEEP for patient 1 which is 888.88 # features/steps/descriptors_are_drawn_to_the_display.py:50
    Then PEEP for patient 1 doesn't overflow                                                                                          # features/steps/descriptors_are_drawn_to_the_display.py:63

Feature: Driver for SFM3300-D Flow Sensor # features/driver_for_sfm3300d.feature:1

  Scenario:                                                 # features/driver_for_sfm3300d.feature:3
    Given an SFM3300-D Flow sensor is connected to hardware # features/steps/driver_for_sfm3300d.py:10
    And the SFM3300-D is initialized                        # None
    Then you can collect flow data                          # None
    And you can collect a serial number                     # None

  Scenario: Can positively inquire about the sensor's presense  # features/driver_for_sfm3300d.feature:9
    Given an SFM3300-D Flow sensor is connected to hardware     # features/steps/driver_for_sfm3300d.py:10
    And the SFM3300-D is initialized                            # None
    Then you can check that the SFM3300-D is in fact present    # None

  Scenario: Can negatively inquire about the sensor's presense   # features/driver_for_sfm3300d.feature:15
    Given an SFM3300-D Flow sensor is not connected to hardware  # features/steps/driver_for_sfm3300d.py:43
    And the SFM3300-D is initialized                             # features/steps/driver_for_sfm3300d.py:18
    Then you can check that the SFM3300-D is in fact not present # features/steps/driver_for_sfm3300d.py:52

Feature: Driver for SPL06-007 Pressure Sensor # features/driver_for_spl06_007.feature:1

  Scenario: Collects valid data                                 # features/driver_for_spl06_007.feature:3
    Given an SPL06-007 Pressure sensor is connected to hardware # features/steps/driver_for_spl06_007.py:13
    And the SPL06-007 is initialized                            # None
    When you set the sampling parameters                        # None
    And you set the op mode to Command                          # None
    Then you can collect pressure data                          # None
    And you can collect temperature data                        # None

  Scenario: Can positively inquire about the sensor's presense  # features/driver_for_spl06_007.feature:12
    Given an SPL06-007 Pressure sensor is connected to hardware # features/steps/driver_for_spl06_007.py:13
    And the SPL06-007 is initialized                            # None
    Then you can check that the SPL06-007 is in fact present    # None

  Scenario: Can negatively inquire about the sensor's presense      # features/driver_for_spl06_007.feature:18
    Given an SPL06-007 Pressure sensor is not connected to hardware # features/steps/driver_for_spl06_007.py:61
    And the SPL06-007 is initialized                                # features/steps/driver_for_spl06_007.py:21
    Then you can check that the SPL06-007 is in fact not present    # features/steps/driver_for_spl06_007.py:70

Feature: gets data from sensors # features/gets_sensor_data.feature:1

  Scenario: connects to the sensors that are connected                                  # features/gets_sensor_data.feature:3
    Given there is an object that represent the total sensing package                   # features/steps/gets_sensor_data.py:13
    When these sensors are initialized                                                  # features/steps/gets_sensor_data.py:19
    Then the software will calibrate the sensors                                        # features/steps/gets_sensor_data.py:24
    Then the software will determine which tubes have both pressure and airflow sensing # features/steps/gets_sensor_data.py:30
    Then the software will return the state of the sensor to the user.                  # features/steps/gets_sensor_data.py:40

  Scenario: there are not enough sensors                              # features/gets_sensor_data.feature:10
    Given there is an object that represent the total sensing package # features/steps/gets_sensor_data.py:13
    And any tube doesn't have a complete set of working sensors       # features/steps/gets_sensor_data.py:48
    When the software diagnostic is run                               # features/steps/gets_sensor_data.py:53
    Then 1 warning NotEnoughSensors will be raised                    # features/steps/gets_sensor_data.py:62

  Scenario: there are multiple airflow sensors on a single tube  # features/gets_sensor_data.feature:16
    Given "SFM3300" sensor on a tube                             # features/steps/gets_sensor_data.py:72
    And "Mass Air Flow" sensor on a tube                         # features/steps/gets_sensor_data.py:72
    When data is read                                            # features/steps/gets_sensor_data.py:77
    Then the data from "Mass Air Flow" will be used              # features/steps/gets_sensor_data.py:82

@wip
Feature: Runs backend from a Docker image # features/runs_backend_from_docker_image.feature:2

  @slow
  Scenario:                                                                    # features/runs_backend_from_docker_image.feature:5
    Given A running Docker image on port 8000                                  # features/steps/runs_backend_from_docker_image.py:10
    When I listen for packets                                                  # features/steps/runs_backend_from_docker_image.py:21
    Then there will be a JSON packet sent every 1.0 seconds                    # features/steps/runs_backend_from_docker_image.py:27
    And that JSON packet will have several keys named with 'patient-{0-index}' # features/steps/runs_backend_from_docker_image.py:41
    And those keys will refer to the descriptors                               # features/steps/runs_backend_from_docker_image.py:50

6 features passed, 0 failed, 0 skipped
10 scenarios passed, 0 failed, 4 skipped
46 steps passed, 0 failed, 16 skipped, 0 undefined
Took 0m28.364s

Process finished with exit code 0

**Comment by mmroden** [comment]
The code behind the test is this:

@given("A running Docker image on port {port}")
def step_impl(context, port):
    context.port = port
    context.client.containers.run(context.container_tag,
                                  name=context.container_name,
                                  detach=True,
                                  auto_remove=True,
                                  ports={f"{context.port}": context.port})
    time.sleep(1.2)  # give the container a moment to start up



@when("I listen for packets")
def step_impl(context):
    uri = f"ws://localhost:{context.port}/ws"
    context.ws = ws_connect_retry(uri)


@then("there will be a JSON packet sent every {t:f} seconds")
def step_impl(context, t):
    number_of_messages = 5
    start_time = time.time()
    for _ in range(number_of_messages):
        context.message = context.ws.recv()
    end_time = time.time()
    context.json = json.loads(context.message)
    context.client.containers.get(context.container_name).kill()
    assert math.isclose((end_time - start_time)/number_of_messages, t,
                        rel_tol=0.15), \
        "Fails to send packets at 1 Hz"

Sleep is already a bad code smell, but I'm not sure how else we want to mimic 5 seconds going past.  

It's possible that there's some kind of block or interference on port 8000 that's causing problems here, or something else in the logic (ie, maybe the ws.recv() is overwriting the previous call and the assert is failing, but then how would it pass?).  I'll take a further look.

**Comment by tonyroberts** [comment]
To make this work on my PC I had to:

- Change the path used in "before_all"

```
def before_all(context):
    context.client = docker.from_env()
    context.container_tag = "zmq_proxy:latest"
    context.container_name = "zmq_proxy"
    context.image = context.client.images.build(path=os.path.join(os.path.dirname(__file__), ".."),
                                                platform="linux/arm/v6",
                                                tag=context.container_tag)
```

- Increase time to allow docker to start to 5 seconds

```
@given("A running Docker image on port {port}")
def step_impl(context, port):
    context.port = port
    context.client.containers.run(context.container_tag,
                                  name=context.container_name,
                                  detach=True,
                                  auto_remove=True,
                                  ports={f"{context.port}": context.port})
    time.sleep(5)  # give the container a moment to start up
```

Hack the chrome webdriver to find the chromedriver as it wasn't picked up off the path

```
@fixture
def browser_chrome(context, timeout=30, **kwargs):
    opts = webdriver.ChromeOptions()
    opts.add_argument('--disable-gpu')
    opts.add_argument('--no-sandbox')
    opts.add_argument('--headless')
    context.browser = webdriver.Chrome(r"C:\Users\tony\Utilities\chromedriver.exe", options=opts)
    yield context.browser
    context.browser.close()
```

I didn't check any of these changes in as I assumed they were specific to my environment if these tests were working for others before, but perhaps not.

Waiting for an arbitrary period to allow docker to start seem particularly fragile and I'm sure that could be improved. That's probably what's causing this test to fail for you since it may take a bit longer to start the container now it's running under qemu.

chromedriverinstall.sh also didn't work for me so I installed it manually (both in linux and Windows land, but couldn't get the tests to find it when running in WSL even after installing it - worked ok running on plain Windows though).

**Comment by mmroden** [comment]
Digging further, on my machine, it's a timing issue-- the server is receiving 5 messages, but receiving them with an average of every 1.5 seconds, not every 1 second.  That's actually critical functionality that we need to resolve.  Could there be some kind of timing issue in production introduced by this change?  Digging further.

**Comment by mmroden** [comment]
I think I've found the issue.  The first message takes 4 seconds to return.  If I change the test to be:

@then("there will be a JSON packet sent every {t:f} seconds")
def step_impl(context, t):
    number_of_messages = 5
    start_time = time.time()
    print(start_time)
    for _ in range(number_of_messages):
        context.message = context.ws.recv()
        print(context.message, time.time())
    end_time = time.time()
    print(end_time)
    context.json = json.loads(context.message)
    context.client.containers.get(context.container_name).kill()
    print ((end_time-start_time)/number_of_messages)
    assert math.isclose((end_time - start_time)/number_of_messages, t,
                        rel_tol=0.15), \
        "Fails to send packets at 1 Hz"

The captured output is: 
      Captured stdout:
      1621455607.891826
      {"patient-0": {"Inspiratory Pressure": 8.259, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-1": {"Inspiratory Pressure": 8.259, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-2": {"Inspiratory Pressure": 8.259, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-3": {"Inspiratory Pressure": 8.259, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}} 1621455611.3739588
      {"patient-0": {"Inspiratory Pressure": 8.431999999999999, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-1": {"Inspiratory Pressure": 8.431999999999999, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-2": {"Inspiratory Pressure": 8.431999999999999, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-3": {"Inspiratory Pressure": 8.431999999999999, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}} 1621455612.375131
      {"patient-0": {"Inspiratory Pressure": 8.456, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-1": {"Inspiratory Pressure": 8.456, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-2": {"Inspiratory Pressure": 8.456, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-3": {"Inspiratory Pressure": 8.456, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}} 1621455613.390914
      {"patient-0": {"Inspiratory Pressure": 8.529, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-1": {"Inspiratory Pressure": 8.529, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-2": {"Inspiratory Pressure": 8.529, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-3": {"Inspiratory Pressure": 8.529, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}} 1621455614.401589
      {"patient-0": {"Inspiratory Pressure": 8.607, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-1": {"Inspiratory Pressure": 8.607, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-2": {"Inspiratory Pressure": 8.607, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}, "patient-3": {"Inspiratory Pressure": 8.607, "PEEP": 8.19944285714285, "PIP": 17, "Tidal Volume": 0, "Flow Rate": 0.0}} 1621455615.409683
      1621455615.4096892
      1.503572654724121

The start time is: 1621455607.891826
but the first packet is received at: 1621455611.3739588
So, the startup sleep time of 1.2 seconds is not long enough.

I will work on a fix, give me a sec.

**Comment by mmroden** [comment]
This patch makes the PR work on my system, can you check it on yours?

diff --git a/features/steps/runs_backend_from_docker_image.py b/features/steps/runs_backend_from_docker_image.py
index 2f17b6b..ee80a2a 100644
--- a/features/steps/runs_backend_from_docker_image.py
+++ b/features/steps/runs_backend_from_docker_image.py
@@ -15,24 +15,33 @@ def step_impl(context, port):
                                   detach=True,
                                   auto_remove=True,
                                   ports={f"{context.port}": context.port})
-    time.sleep(1.2)  # give the container a moment to start up
+    time.sleep(2.0)  # give the container a moment to start up.
+    # Has a bad code smell, but it takes a second or two for things to start.
+    # Even so, further listening is done in the "I listen for packets" step to
+    # make sure we have good timing once everything's running
 
 
 @when("I listen for packets")
 def step_impl(context):
     uri = f"ws://localhost:{context.port}/ws"
     context.ws = ws_connect_retry(uri)
+    context.first_message = context.ws.recv()  # triggers waiting for the first
+    # message to appear, rather than sleeping for it
 
 
 @then("there will be a JSON packet sent every {t:f} seconds")
 def step_impl(context, t):
     number_of_messages = 5
     start_time = time.time()
+    print(start_time)  # leaving in print statements for later debugging if necessary
     for _ in range(number_of_messages):
         context.message = context.ws.recv()
+        print(context.message, time.time())
     end_time = time.time()
+    print(end_time)
     context.json = json.loads(context.message)
     context.client.containers.get(context.container_name).kill()
+    print ((end_time-start_time)/number_of_messages)
     assert math.isclose((end_time - start_time)/number_of_messages, t,
                         rel_tol=0.15), \
         "Fails to send packets at 1 Hz"

in non git-diff form:

@given("A running Docker image on port {port}")
def step_impl(context, port):
    context.port = port
    context.client.containers.run(context.container_tag,
                                  name=context.container_name,
                                  detach=True,
                                  auto_remove=True,
                                  ports={f"{context.port}": context.port})
    time.sleep(2.0)  # give the container a moment to start up.                                                                                                                                                                  
    # Has a bad code smell, but it takes a second or two for things to start.                                                                                                                                                    
    # Even so, further listening is done in the "I listen for packets" step to                                                                                                                                                   
    # make sure we have good timing once everything's running                                                                                                                                                                    


@when("I listen for packets")
def step_impl(context):
    uri = f"ws://localhost:{context.port}/ws"
    context.ws = ws_connect_retry(uri)
    context.first_message = context.ws.recv()  # triggers waiting for the first                                                                                                                                                  
    # message to appear, rather than sleeping for it                                                                                                                                                                             


@then("there will be a JSON packet sent every {t:f} seconds")
def step_impl(context, t):
    number_of_messages = 5
    start_time = time.time()
    print(start_time)  # leaving in print statements for later debugging if necessary                                                                                                                                            
    for _ in range(number_of_messages):
        context.message = context.ws.recv()
        print(context.message, time.time())
    end_time = time.time()
    print(end_time)
    context.json = json.loads(context.message)
    context.client.containers.get(context.container_name).kill()
    print ((end_time-start_time)/number_of_messages)
    assert math.isclose((end_time - start_time)/number_of_messages, t,
                        rel_tol=0.15), \
        "Fails to send packets at 1 Hz"

**Comment by mmroden** [comment]
Yeah, so we got to the same answer-- the only real difference is that I'm waiting for the first message to come from the server before proceeding, which I think feels safer, but I agree that it's not the best solution.  I would accept that wait for the first message for now.

**Comment by tonyroberts** [comment]
Great, yep that sounds like a good solution for now 👍

**Review by mmroden — APPROVED** [review]
Approved once we got the tests to pass

**Comment by mmroden** [comment]
Let me check the directory changes and the chrome fixture changes as well.  If you need those on windows and they don't affect the mac, then I'll add them.

**Comment by mmroden** [comment]
OK, I added the context.client.images.build change, but I don't think I can add a change to your specific windows user directory :)  If there's a way to generalize that, I'm about it.  I don't like that windows requires a separate way to make this work, maybe it has to be some kind of OS-specific flag?

**Comment by Judoguy12** [comment]
Ready to merge?

**Comment by tonyroberts** [comment]
@mmroden I think it's fine to leave the chrome thing as it is. I'm sure it's just something that's wrong in my environment and nothing to worry about.

**Pull request merged**
