### PR TITLE
fixed the errors that came out of the bad merge.  Closes #3

### LINKED ISSUE #3: Fix errors coming out of a bad merge

### PR DESCRIPTION
**Pull request by fpdotmonkey**
To test, run this
```bash
$ ./setup.sh
$ . venv/bin/activate
$ ./runtests.sh
```
Several tests should be skipped, but none should fail.

### CODE REVIEW

**Comment by capsulecorplab** [comment]
I'm getting the following after running `./runtests.sh`. Also `setup.sh` isn't activating the virtual environment, if it should.
```
Behaviour Tests:
HOOK-ERROR in before_all: ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))
HOOK-ERROR in after_all: ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

ABORTED: By user.
0 features passed, 0 failed, 0 skipped, 5 untested
0 scenarios passed, 0 failed, 0 skipped, 11 untested
0 steps passed, 0 failed, 0 skipped, 0 undefined, 43 untested
Took 0m0.000s
$
Unit Tests:
...........................................sssss.....................sss........
----------------------------------------------------------------------
Ran 80 tests in 3.618s

OK (skipped=8)
```

**Comment by fpdotmonkey** [comment]
You have to manually activate the venv.  I did it that way in case the user didn't want to immediately work in the venv for some reason.  Weird that the behave tests aren't working.  They're defo working for me

**Comment by fpdotmonkey** [comment]
@capsulecorplab can you run `git log`

**Comment by capsulecorplab** [comment]
@fpdotmonkey I checked out cf1f796, if that's what you're wondering

**Comment by fpdotmonkey** [comment]
@capsulecorplab did you have the container for the docs website running when you tried to run the tests?  I had the behave tests fail just now, and shutting down that container made it pass (idk why).

**Comment by capsulecorplab** [comment]
@fpdotmonkey no other containers running

**Pull request merged**
